version: "2.0"

volumes:
    mysql_bkp_orderdb:
    mysql_bkp_labtestdb:

services:
  lab_test_db:
    container_name: lab_test_mysql_db
    image: mysql:5.6
    volumes:
      - mysql_bkp_labtestdb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: flebiedb
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: flebieuser
      MYSQL_PASSWORD: passw0rd
    
  keycloak_db:
    container_name: keycloak_mysql_db
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: keycloakdb
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: flebieuser
      MYSQL_PASSWORD: passw0rd

  order_mgmt_db:
    container_name: order_mgmt_mysql_db
    image: mysql:5.6
    volumes:
      - mysql_bkp_orderdb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: flebieuser
      MYSQL_PASSWORD: passw0rd

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    #volumes:
    #  - ./rabbitmq.config:/var/lib/rabbitmq/config/generated/rabbitmq.config
    #  - ./rabbit_create_users.sh:/rabbit_create_users.sh
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672
  
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    hostname: keycloak
    restart: on-failure
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloakdb
      DB_USER: flebieuser
      DB_PASSWORD: passw0rd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      #KEYCLOAK_IMPORT: /tmp/realm.json
      KEYCLOAK_LOGLEVEL: FATAL
    depends_on:
       - keycloak_db
    ports:
      - 8080:8080
  
  flebie-eureka-naming-server:
    container_name: flebie-eureka-naming-server
    image: flebie-eureka-naming-server
    ports:
      - 8761:8761

  flebie-lab-test-service:
    container_name: flebie-lab-test-service
    image: flebie-lab-test-service:latest
    ports:
      - 8980:8980
    restart: on-failure
    environment:
      SPRING_DATASOURCE_USERNAME: flebieuser
      SPRING_DATASOURCE_PASSWORD: passw0rd
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://flebie-eureka-naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://lab_test_db:3306/flebiedb
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      #SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: rabbitmq
      SPRING_RABBITMQ_PASSWORD: rabbitmq
  
  flebie-order-management-service:
    container_name: flebie-order-management-service
    image: flebie-order-management-service:latest
    restart: on-failure
    ports:
      - 9081:9081
    environment:
      SPRING_DATASOURCE_USERNAME: flebieuser
      SPRING_DATASOURCE_PASSWORD: passw0rd
      SPRING_DATASOURCE_URL: jdbc:mysql://order_mgmt_db:3306/orderdb
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://flebie-eureka-naming-server:8761/eureka
      AWS_REGION: us-east-1
      AWS_ENDPOINT: http://localhost:10001
      AWS_ACCESS_KEY_ID: 123
      AWS_SECRET_ACCESS_KEY: abc
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: rabbitmq
      RABBITMQ_PASSWORD: rabbitmq

  flebie-frontend-service:
    container_name: flebie-frontend-service
    image: flebie-frontend:latest
    ports:
      - 3000:3000
 
  