version: "2.0"

volumes:
    mysql_bkp_orderdb:
    mysql_bkp_labtestdb:
    mysql_bkp_keycloakdb:
    mysql_bkp_visitdb:
    mysql_bkp_clientdb:
    mysql_bkp_availabilitydb:
    mysql_bkp_accountdb:
    mysql_bkp_clientlookupdb:

services:
  lab_test_db:
    container_name: lab_test_mysql_db
    image: mysql:5.6
    volumes:
      - mysql_bkp_labtestdb:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: flebiedb_flebie
      MYSQL_ROOT_PASSWORD: password
    
  keycloak_db:
    container_name: keycloak_mysql_db
    image: mysql:5.6
    volumes:
      - mysql_bkp_keycloakdb:/var/lib/mysql
    ports:
      - 3333:3306
    environment:
      MYSQL_DATABASE: keycloakdb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: flebieuser
      MYSQL_PASSWORD: passw0rd

  order_mgmt_db:
    container_name: order_mgmt_mysql_db
    image: mysql:5.6
    volumes:
      - mysql_bkp_orderdb:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: orderdb_flebie
      MYSQL_ROOT_PASSWORD: password

  order_fulflmnt_db:
    container_name: order_fulflmnt_mysql_db
    image: mysql:5.6
    volumes:
      - mysql_bkp_visitdb:/var/lib/mysql
    ports:
      - 33062:3306
    environment:
      MYSQL_DATABASE: visitdb
      MYSQL_ROOT_PASSWORD: password

  availability_db:
    container_name: availability_mysql_db
    image: mysql:5.6
    volumes:
      - mysql_bkp_availabilitydb:/var/lib/mysql
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: availabilitydb_flebie
      MYSQL_ROOT_PASSWORD: password

  client_db:
    container_name: client_mysql_db
    image: mysql:5.6
    volumes:
      - mysql_bkp_clientdb:/var/lib/mysql
    ports:
      - 33064:3306
    environment:
      MYSQL_DATABASE: clientdb_flebie
      MYSQL_ROOT_PASSWORD: password

  account_db:
    container_name: account_mysql_db
    image: mysql:5.6
    volumes:
      - mysql_bkp_accountdb:/var/lib/mysql
    ports:
      - 33063:3306
    environment:
      MYSQL_DATABASE: accountdb_flebie
      MYSQL_ROOT_PASSWORD: password

  clientlookup_db:
    container_name: clientlookup_mysql_db
    image: mysql:5.6
    volumes:
      - mysql_bkp_clientlookupdb:/var/lib/mysql
    ports:
      - 33065:3306
    environment:
      MYSQL_DATABASE: clientlookupdb
      MYSQL_ROOT_PASSWORD: password

  rabbitmq-container:
    container_name: rabbitmq-container
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672
  
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    hostname: keycloak
    restart: on-failure
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloakdb
      DB_USER: flebieuser
      DB_PASSWORD: passw0rd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    depends_on:
       - keycloak_db
    ports:
      - 8080:8080

  flebie-eureka-naming-server:
    container_name: flebie-eureka-naming-server
    image: flebie-eureka-naming-server:latest
    ports:
      - 8761:8761

  flebie-config-server:
    container_name: flebie-config-server
    image: flebie-config-server:latest
    ports:
      - 8888:8888

  flebie-lab-test-service:
    container_name: flebie-lab-test-service
    image: flebie-lab-test-service:latest
    ports:
      - 9000:9000
      - 7000:7000
    restart: always
    environment:
      SPRING_CLOUD_CONFIG_URI: http://flebie-config-server:8888
      KEYCLOAK_AUTH_SERVER_URL: ${EXTERNAL_IP}
      #KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      SERVICE_URL_DEFAULT_ZONE: http://flebie-eureka-naming-server:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq-container
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: rabbitmq
      SPRING_RABBITMQ_PASSWORD: rabbitmq
      DBHOST: lab_test_db
  
  flebie-order-management-service:
    container_name: flebie-order-management-service
    image: flebie-order-management-service:latest
    restart: on-failure
    ports:
      - 9001:9001
      - 7001:7001
    environment:
      SPRING_CLOUD_CONFIG_URI: http://flebie-config-server:8888
      KEYCLOAK_AUTH_SERVER_URL: ${EXTERNAL_IP}
      #KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      SERVICE_URL_DEFAULT_ZONE: http://flebie-eureka-naming-server:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq-container
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: rabbitmq
      SPRING_RABBITMQ_PASSWORD: rabbitmq
      DBHOST: order_mgmt_db

  flebie-order-fulfillment-service:
    container_name: flebie-order-fulfillment-service
    image: flebie-order-fulfillment-service:latest
    restart: on-failure
    ports: 
      - 9002:9002
      - 7002:7002
    environment:
      SPRING_CLOUD_CONFIG_URI: http://flebie-config-server:8888
      KEYCLOAK_AUTH_SERVER_URL: ${EXTERNAL_IP}
      #KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      SERVICE_URL_DEFAULT_ZONE: http://flebie-eureka-naming-server:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq-container
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: rabbitmq
      SPRING_RABBITMQ_PASSWORD: rabbitmq
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:mysql://order_fulflmnt_db:3306/visitdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver

  flebie-availability-service:
    container_name: flebie-availability-service
    image: flebie-availability-service:latest
    restart: on-failure
    ports:
      - 9006:9006
      - 7006:7006
    environment:
      SPRING_CLOUD_CONFIG_URI: http://flebie-config-server:8888
      KEYCLOAK_AUTH_SERVER_URL: ${EXTERNAL_IP}
      #KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      SERVICE_URL_DEFAULT_ZONE: http://flebie-eureka-naming-server:8761/eureka
      DBHOST: availability_db

  flebie-client-management-service:
    container_name: flebie-client-management-service
    image: flebie-client-management-service:latest
    restart: on-failure
    ports:
      - 9004:9004
      - 7004:7004
    environment:
      SPRING_CLOUD_CONFIG_URI: http://flebie-config-server:8888
      KEYCLOAK_AUTH_SERVER_URL: ${EXTERNAL_IP}
      #KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      SERVICE_URL_DEFAULT_ZONE: http://flebie-eureka-naming-server:8761/eureka
      DBHOST: client_db
      
  flebie-account-management-service:
    container_name: flebie-account-management-service
    image: flebie-account-management-service:latest
    restart: on-failure
    ports:
      - 9003:9003
      - 7003:7003
    environment:
      SPRING_CLOUD_CONFIG_URI: http://flebie-config-server:8888
      KEYCLOAK_AUTH_SERVER_URL: ${EXTERNAL_IP}
      #KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      SERVICE_URL_DEFAULT_ZONE: http://flebie-eureka-naming-server:8761/eureka
      DBHOST: account_db

  flebie-client-notification-service:
    container_name: flebie-client-notification-service
    image: flebie-client-notification-service:latest
    restart: on-failure
    ports:
      - 9005:9005
      - 7005:7005
    environment:
      SPRING_CLOUD_CONFIG_URI: http://flebie-config-server:8888
      KEYCLOAK_AUTH_SERVER_URL: ${EXTERNAL_IP}
      #KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      SERVICE_URL_DEFAULT_ZONE: http://flebie-eureka-naming-server:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq-container
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: rabbitmq
      SPRING_RABBITMQ_PASSWORD: rabbitmq
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:mysql://clientlookup_db:3306/clientlookupdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver

  flebie-frontend-service:
    container_name: flebie-frontend-service
    image: flebie-frontend:latest
    ports:
      - 3000:3000

  flebie-external-notification-service:
    container_name: flebie-external-notification-service
    image: flebie-external-notification-service:latest
    restart: on-failure
    ports:
      - 9007:9007
      - 7007:7007
    environment:
      SPRING_CLOUD_CONFIG_URI: http://flebie-config-server:8888
      KEYCLOAK_AUTH_SERVER_URL: ${EXTERNAL_IP}
      #KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      SERVICE_URL_DEFAULT_ZONE: http://flebie-eureka-naming-server:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq-container
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: rabbitmq
      SPRING_RABBITMQ_PASSWORD: rabbitmq
